service: chuisheet
provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1
  memorySize: 128 # set the maximum memory of the Lambdas in Megabytes
  timeout: 10 # the timeout is 10 seconds (default is 6 seconds)
  environment:
    DB: ${file(./variables.json):DB}
    SPACES_KEY: ${file(./variables.json):SPACES_KEY}
    SPACES_SECRET: ${file(./variables.json):SPACES_SECRET}
    
functions:
  get:
    handler: handler.port
    events:
      - http:
          method: any
          path: /
          cors: true
      - http:
          method: any
          path: /{site}
          cors: true
      - http:
          method: any
          path: /{site}/{chain}
          cors: true
      - http:
          method: any
          path: /{site}/{chain}/{arg1}
          cors: true
      - http:
          method: any
          path: /{site}/{chain}/{arg1}/{arg2}
          cors: true
